### ISSUE TITLE
bw_bed

### ISSUE THREAD

**Issue by simonelsasser** [elsasserlab/labcode#32] opened 2020-06-17 13:45 UTC
got this error after some computing time - seems like all the files were legit though

> bins <- bw_bed(bwfiles, loci, per.locus.stat = "mean", aggregate.by = NULL)
Error in `[[<-`(`*tmp*`, name, value = c("tss_hi", "tss_hi", "tss_hi",  : 
  5874 elements in value to replace 52146 elements

**Comment by cnluzon** [comment] 2020-06-17 13:49
That may be some handling of the name field from the `BED` file. Can you send/point me to this file so I can try to reproduce the error?

**Comment by cnluzon** [comment] 2020-06-17 13:54
Oh, also I would try to reinstall `elsasserlib` fresh, I changed multiple things (including unit tests for bw functions) since last time so that may have already fixed some problems.

If that doesn't fix it, it would be also great if you can show the output of `sessionInfo()` in Rstudio.

**Comment by simonelsasser** [comment] 2020-06-17 14:58
[biv_tss.txt](https://github.com/elsasserlab/labcode/files/4793346/biv_tss.txt)

**Comment by cnluzon** [comment] 2020-06-17 15:35
It works for me:

    > bw_bed('./bw_test/abigwig.mm9.bs5.bw', './biv_tss.bed', aggregate.by=NULL)
    GRanges object with 5874 ranges and 2 metadata columns:
             seqnames              ranges strand | abigwig.bs5.bw        name
                <Rle>           <IRanges>  <Rle> |           <numeric> <character>
         [1]     chr1     3660178-3663163      + |    15.8180730996001    bivalent
         [2]     chr1     4481312-4484482      + |    29.6473876646512    bivalent
         [3]     chr1     4560997-4562781      + |    17.5935537948662    bivalent
         [4]     chr1     4774808-4776807      - |    9.71674319672585      tss_hi
         [5]     chr1     4796974-4798973      + |     22.915706410408      tss_hi

Note: `loci` must be a filename, and it should have `bed` extension -> I'm going to add some warning or fix for this.

But in my case, if I just provide `biv_tss.txt` I get an error like:

    Error in FileForFormat(con) : Format 'txt' unsupported

coming from `rtracklayer`. Nothing like the error you get.

Another issue I'm fixing is that R by default replaces columns with filenames, but if these contain `-` or strange characters it will convert them to `.` and crash after because there is no correspondence filename <-> column anymore. So another thing you can try is to remove such characters from your filenames.

There may also be an issue with versions of packages. Can you show me your `sessionInfo()` output if none of this works?

1. Reinstall package fresh (add `force=TRUE` to the `github_install` call, to make sure it overwrites it).
2. Change extension `txt` -> `bed`.
3. Clean up `bw` names.

**Comment by simonelsasser** [comment] 2020-06-17 22:23
updated elsasserlib install but same error 

```
sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] remotes_2.1.1        dplyr_1.0.0          rtracklayer_1.47.0   GenomicRanges_1.40.0 GenomeInfoDb_1.24.0 
 [6] IRanges_2.22.2       S4Vectors_0.26.1     BiocGenerics_0.34.0  ggpubr_0.3.0         reshape2_1.4.4      
[11] ggplot2_3.3.1        elsasserlib_0.1.0   

loaded via a namespace (and not attached):
 [1] Biobase_2.48.0                    tidyr_1.1.0                       carData_3.0-4                    
 [4] assertthat_0.2.1                  BSgenome_1.56.0                   GenomeInfoDbData_1.2.3           
 [7] cellranger_1.1.0                  Rsamtools_2.4.0                   pillar_1.4.4                     
[10] backports_1.1.7                   lattice_0.20-41                   glue_1.4.1                       
[13] ggsignif_0.6.0                    XVector_0.28.0                    colorspace_1.4-1                 
[16] Matrix_1.2-18                     plyr_1.8.6                        XML_3.99-0.3                     
[19] pkgconfig_2.0.3                   broom_0.5.6                       haven_2.3.1                      
[22] zlibbioc_1.34.0                   purrr_0.3.4                       scales_1.1.1                     
[25] processx_3.4.2                    openxlsx_4.1.5                    rio_0.5.16                       
[28] BiocParallel_1.22.0               tibble_3.0.1                      generics_0.0.2                   
[31] car_3.0-8                         ellipsis_0.3.1                    withr_2.2.0                      
[34] SummarizedExperiment_1.18.1       cli_2.0.2                         magrittr_1.5                     
[37] crayon_1.3.4                      readxl_1.3.1                      ps_1.3.3                         
[40] fansi_0.4.1                       nlme_3.1-147                      BSgenome.Mmusculus.UCSC.mm9_1.4.0
[43] rstatix_0.5.0                     forcats_0.5.0                     foreign_0.8-78                   
[46] pkgbuild_1.0.8                    prettyunits_1.1.1                 tools_4.0.0                      
[49] data.table_1.12.8                 hms_0.5.3                         lifecycle_0.2.0                  
[52] matrixStats_0.56.0                stringr_1.4.0                     munsell_0.5.0                    
[55] zip_2.0.4                         DelayedArray_0.14.0               callr_3.4.3                      
[58] Biostrings_2.56.0                 compiler_4.0.0                    rlang_0.4.6                      
[61] grid_4.0.0                        RCurl_1.98-1.2                    rstudioapi_0.11                  
[64] bitops_1.0-6                      gtable_0.3.0                      abind_1.4-5                      
[67] curl_4.3                          R6_2.4.1                          GenomicAlignments_1.24.0         
[70] rprojroot_1.3-2                   stringi_1.4.6                     Rcpp_1.0.4.6                     
[73] vctrs_0.3.0                       tidyselect_1.1.0                  BSgenome.Hsapiens.UCSC.hg38_1.4.3
```

I did have a .bed extension, just GitHub didn't allow me to upload it ;)

**Comment by simonelsasser** [comment] 2020-06-17 22:29
if I run with just two of the files, same error but different numbers:
```
bins <- as.data.frame(bw_bed(bwfiles[1:2], loci))
Error in `[[<-`(`*tmp*`, name, value = c("bivalent", "bivalent", "bivalent",  : 
  5874 elements in value to replace 6126 elements
```

**Comment by cnluzon** [comment] 2020-06-18 09:37
Finally reproduced this: it's a bit of a mysterious one, I'm looking into it. It seems to be related to the fact that this `tss_biv` file contains a few overlapping regions. But it's strange because it only happens with multiple `bw` files, so I'm thinking maybe there is some automatic merging happening that depends on the actual values.

If you need an immediate workaround, merging overlapping regions in the bed file seems to fix this.

**Comment by cnluzon** [comment] 2020-06-18 13:17
I think it should work now @simonelsasser , the automated tests now run for a release of ubuntu, MacOS and Windows, and locally I tried with the same `BED` file and worked. But let me know if you still encounter this problem.

The fix required reimplementing manually the merging of `GRanges` objects, as this `cbind`-like functionality does not seem to be provided (AFAIK). So now I basically calculate one GRanges for each `bigWig`-`BED` intersection, sort them all and combine them column-wise. 

Technically, sorting is not requried as `bigWig` summary from `rtracklayer` seems to keep the order of the loci, but I thought it's safer to sort it and it's good have a sorted output.

But let me know also if you experience a lot of overhead, I don't and I think it does not add a lot of computing to it.

**Comment by cnluzon** [comment] 2020-07-02 15:11
This problem seems to have resurfaced to me on R 4 on the new installation:

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=sv_SE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=sv_SE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=sv_SE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RColorBrewer_1.1-2 pheatmap_1.0.12    stringr_1.4.0      ggpubr_0.4.0       reshape2_1.4.4     ggplot2_3.3.2      elsasserlib_0.1.1 

loaded via a namespace (and not attached):
 [1] Biobase_2.48.0                    tidyr_1.1.0                       carData_3.0-4                     stats4_4.0.2                     
 [5] BSgenome_1.56.0                   GenomeInfoDbData_1.2.3            cellranger_1.1.0                  Rsamtools_2.4.0                  
 [9] yaml_2.2.1                        pillar_1.4.4                      backports_1.1.8                   lattice_0.20-41                  
[13] glue_1.4.1                        digest_0.6.25                     GenomicRanges_1.40.0              ggsignif_0.6.0                   
[17] XVector_0.28.0                    colorspace_1.4-1                  htmltools_0.5.0                   Matrix_1.2-18                    
[21] plyr_1.8.6                        XML_3.99-0.3                      pkgconfig_2.0.3                   broom_0.5.6                      
[25] haven_2.3.1                       zlibbioc_1.34.0                   purrr_0.3.4                       scales_1.1.1                     
[29] openxlsx_4.1.5                    rio_0.5.16                        BiocParallel_1.22.0               tibble_3.0.1                     
[33] farver_2.0.3                      generics_0.0.2                    IRanges_2.22.2                    car_3.0-8                        
[37] ellipsis_0.3.1                    withr_2.2.0                       SummarizedExperiment_1.18.1       BiocGenerics_0.34.0              
[41] magrittr_1.5                      crayon_1.3.4                      readxl_1.3.1                      evaluate_0.14                    
[45] nlme_3.1-147                      BSgenome.Mmusculus.UCSC.mm9_1.4.0 rstatix_0.6.0                     forcats_0.5.0                    
[49] foreign_0.8-79                    tools_4.0.2                       data.table_1.12.8                 hms_0.5.3                        
[53] lifecycle_0.2.0                   matrixStats_0.56.0                S4Vectors_0.26.1                  munsell_0.5.0                    
[57] zip_2.0.4                         DelayedArray_0.14.0               Biostrings_2.56.0                 compiler_4.0.2                   
[61] GenomeInfoDb_1.24.2               rlang_0.4.6                       grid_4.0.2                        RCurl_1.98-1.2                   
[65] rstudioapi_0.11                   labeling_0.3                      bitops_1.0-6                      rmarkdown_2.3                    
[69] gtable_0.3.0                      abind_1.4-5                       curl_4.3                          R6_2.4.1                         
[73] GenomicAlignments_1.24.0          knitr_1.29                        dplyr_1.0.0                       rtracklayer_1.48.0               
[77] stringi_1.4.6                     parallel_4.0.2                    Rcpp_1.0.4.6                      vctrs_0.3.1                      
[81] tidyselect_1.1.0                  xfun_0.15                         BSgenome.Hsapiens.UCSC.hg38_1.4.3
``` 
Oddly enough I get it with `ChromHMM` file but not if I subsample it:

```
Error in `[[<-`(`*tmp*`, name, value = c(505579, 1)) : 
  2 elements in value to replace 505579 elements 
```

**Closed as completed** 2020-07-03 10:34 UTC
