### ISSUE TITLE
Use files from remote location (webexport)

### ISSUE THREAD

**Issue by simonelsasser** [elsasserlab/labcode#36] opened 2020-06-17 15:57 UTC
@cnluzon maybe you already knew this but one can load files from remote url just as well as local.
While this seems a bit slow at home internet connection, I guess it would be a super universal way to pull data without every downloading big files. 

this works:
```
test <- bw_bed("https://export.uppmax.uu.se/snic2020-6-3/Navarro/bw/Banaszynski_2013/2013_Banaszynski_Control_Catch-it.mm9.bw", loci)
```

**Comment by cnluzon** [comment] 2020-06-22 13:29
This is a very cool idea! It's nice that the import will work for URLs as well.

However I get some problems running `rtracklayer::import` for `bigWig` files now, but I don't recall this happening before. This seems to have worked in the past, but now if I simply try: 

    rtracklayer::import("https://export.uppmax.uu.se/snic2020-6-3/Navarro/bw/Banaszynski_2013/2013_Banaszynski_Control_Catch-it.mm9.bw")

I get an error. The URL exists and I can download it, though.

@simonelsasser Can you confirm whether this (`import` and/or `bw_bed`) still works on your MacOS:

a) Your currently installed version of the `elsasserlib` package.
b) An updated version (if you reinstall `elsasserlib`).

I have also validated that:

1) `import` and `bw_bed` still works with BED remote files and local bigWig, so it seems to be a bigWig remote import problem only.
2) If I download the URL that fails and run `bw_bed` or `import` on the downloaded file, it also works, so it is not a corrupted file or something like this.
3) webexport access works as well, so it is not a permissions/URL problem, since BED file was loaded from webexport.
4) Both R 3.6 and R 4.0 give me this error in linux (Ubuntu 16.4 and Uppmax, which I think is CentOS), so it does not seem to be a R major update problem either.

My money is on a `rtracklayer` update and/or older Linux distros thing (`rtracklayer` has been updated lately from 1.47 -> 1.48 but I haven't tracked down the source changes).

**Comment by cnluzon** [comment] 2020-06-22 13:56
Nevermind the remote, the problem seems to reproduce for other local `bw` files, even though the unit tests still work perfectly, so I will further test the summary functions.

**Comment by cnluzon** [comment] 2020-06-22 14:52
This is very puzzling. I do not manage to make it work native with `import` function unless it's BED files. In the documentation of `BigWigFile` it says "connections" are not supported, but I don't know if this was the case before.

But I think this is useful functionality. So I am implementing a fix for this, where `bw_ranges` function now checks if what was given is an URL and tries to download it to a temporary file.

The cool thing about the workaround being implemented within `bw_ranges` is that it will check if it is an URL on a per-file basis, so now it will work with a mix of local files and remote bw files.

The bad thing is that it will download it each time, so no caching implemented so far.

**Closed as completed** 2020-09-30 10:11 UTC
